# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-02 02:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pwdsvc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='uid',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='group',
            name='gid',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
